name: Complex

on:
  push:
    paths:
      - 'php/complex/**'
      - '.github/workflows/complex.yml'
    workflow_dispatch:

jobs:

  frontend:
    uses: andrejvysny/workflows/.github/workflows/docker_build_push_ghcr.yaml@main
    with:
      context: ./php/complex/fe/
      tags: ghcr.io/andrejvysny/complex-fe
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}

  backend:
    uses: andrejvysny/workflows/.github/workflows/docker_build_push_ghcr.yaml@main
    with:
      context: ./php/complex/be/
      tags: ghcr.io/andrejvysny/complex-be
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}