name: Deploy Versions

on:
  push:
    paths:
      - 'deploy/versions/**'
      - '.github/workflows/deploy-version.yml'
  workflow_dispatch:

jobs:

  build_and_push:
    uses: andrejvysny/workflows/.github/workflows/docker_build_push_ghcr.yaml@main
    with:
      context: ./deploy/versions/
      tags: ghcr.io/andrejvysny/deploy-versions:${{github.sha}}
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}