name: PHP Apache - Build and Push Image

on:
  workflow_dispatch:

jobs:
 
  build_and_push:
    uses: andrejvysny/workflows/.github/workflows/docker_build_push_ghcr.yaml@main
    with:
      context: ./php/php-apache/
      tags: ghcr.io/andrejvysny/php-apache:8.1
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}