name: PHP Apache

on:
  push:
    paths:
      - 'php/php-apache/**'
      - '.github/workflows/php-apache.yml'

jobs:
 
  build_and_push:
    uses: andrejvysny/workflows/.github/workflows/docker_build_push_ghcr.yaml@main
    with:
      context: ./php/php-apache/
      tags: ghcr.io/andrejvysny/php-apache:8.3
    secrets:
      access_token: ${{ secrets.GITHUB_TOKEN }}