name: PHP Apache

on:
  push:
    paths:
      - 'php/php-apache/**'
      - '.github/workflows/php-apache.yml'


jobs:
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: **Checkout code**
        uses: actions/checkout@v3

      - name: **Login to GHCR**
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: **Set up QEMU**
        uses: docker/setup-qemu-action@v3

      - name: **Set up Docker Buildx**
        uses: docker/setup-buildx-action@v3

      - name: **Build & push AMD64 image**
        uses: docker/build-push-action@v6
        with:
          context: ./php/php-apache/
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/php-apache:8.3

  build-arm64:
    runs-on: macos-latest
    steps:
      - name: **Checkout code**
        uses: actions/checkout@v3

      - name: **Login to GHCR**
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: **Set up QEMU**
        uses: docker/setup-qemu-action@v3

      - name: **Set up Docker Buildx**
        uses: docker/setup-buildx-action@v3

      - name: **Build & push ARM64 image**
        uses: docker/build-push-action@v6
        with:
          context: ./php/php-apache/
          push: true
          platforms: linux/arm64
          tags: ghcr.io/${{ github.repository_owner }}/php-apache:8.3
