name: PHP Apache

on:
  push:
    paths:
      - 'php/php-apache/**'
      - '.github/workflows/php-apache.yml'

jobs:
  docker_build:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ./php/php-apache/
          tags: ghcr.io/andrejvysny/php-apache:8.3
          push: true
          platforms: linux/amd64


  docker_build_arm:
    name: Docker Build and Push
    runs-on: ubuntu-latest-arm
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: ./php/php-apache/
          tags: ghcr.io/andrejvysny/php-apache:8.3
          push: true
          platforms: linux/arm64
