name: ACA - test
on: 
  workflow_dispatch:


permissions:
      id-token: write
      contents: read

jobs: 
  tag:
    outputs:
      short: ${{ steps.commit.outputs.short }}
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{steps.commit.outputs.short}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""  
  deploy:

    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Echo
        run: |
         echo ${{needs.tag.outputs.short}}
         echo ${{github.sha}}

