name: ACA - test
on: 
  workflow_dispatch:


jobs: 
  tag:
    outputs:
      short: ${{ steps.commit.outputs.short }}
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - uses: actions/checkout@v2
    
  deploy:

    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Echo
        run: |
         echo ${{needs.tag.outputs.short}}
         echo ${{github.sha}}

