on:
  workflow_dispatch:
    inputs:
      myCommit:
        description: 'Commit SHA1'
        required: true
        default: 'undefined'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: echo "building:" ${{ inputs.myCommit }}